name: Feature Request
description: Suggest a feature
labels: feature
body:
  - type: input
    attributes:
      label: Summary
      description: >
        A short summary of what your feature request is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Problem
      description: >
        What problem is your feature trying to solve? What becomes easier or possible
        when this feature is implemented?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Ideal Solution
      description: >
        What is your ideal solution to the problem? What would you like this feature to
        do?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Potential Alternatives
      description: >
        Are there any alternatives that could be used?
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context
      description: If there is anything else to say, please do so here.
